 import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "next hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className=" bg-red-400">
          
          <ul className="flex gap-4 justify-evenly">
            <h4>logo</h4>
            <li>About</li>
            <li>Service</li>
            <li>Contact</li>
          </ul>
        </nav>
        {children}
        <footer className="bg-orange-500">
          this is footer
        </footer>
      </body>
    </html>
  );
}
